# Profile load time using the unix command zprof after startup
zmodload zsh/zprof

# Path to your oh-my-zsh installation
export ZSH="/Users/johannes/.oh-my-zsh"

# Add path for my custom commands (eg. tat)
export PATH="$HOME/bin:/usr/local/sbin:$PATH"

# Add path for composer
export PATH="$HOME/.composer/vendor/bin:$PATH"

# Navigate folders more easily with CDPATH
setopt auto_cd
export CDPATH="$PATH:/Users/johannes/Code:/Users/johannes/Sites:/Users/johannes/Documents:/Users/johannes/Documents/08_FH:/Users/johannes/Documents/01_studio"

# Lazy load nvm to massively reduce zsh startup time
export NVM_NO_USE=true
export NVM_LAZY_LOAD=true

# Lazy load rbenv
rbenv() {
  eval "$(command rbenv init -)"
  rbenv "$@"
}

# Add plugins wisely, as too many of them slow down shell startup.
plugins=(
  git
  zsh-nvm
  zsh-autosuggestions
  zsh-syntax-highlighting
)

# Use OH MY ZSH
source $ZSH/oh-my-zsh.sh

# Reduce startup time by disabling oh-my-zsh's update prompting
DISABLE_UPDATE_PROMPT=true

# Use the pure shell
ZSH_THEME=""
autoload -U promptinit; promptinit
prompt pure

# Set your language environment
export LANG=de_DE.UTF-8

# Preferred editor for local and remote sessions
export EDITOR='vim'

# More settings
for zsh_source in $HOME/dotfiles/zsh/configs/*.zsh; do
  source $zsh_source
done

ensure_tmux_is_running

